# .circleci/config.yml
version: 2.0
jobs:
  build-and-test:
    machine:
      xcode: "10.1.0"
    working_directory: ~/wrk
    environment:
      FL_OUTPUT_DIR: output

    steps:
      - checkout
      - run:
        xcodebuild test -project FastEye.xcodeproj -scheme FastEye -sdk iphonesimulator -destination 'platform=iOS Simulator,name=iPhone 8,OS=12.1'
      - store_test_results:
          path: output/scan
      - store_artifacts:
          path: output

  swiftlint:
    docker:
      - image: dantoml/swiftlint:latest
    steps:
      - checkout
      - run: swiftlint lint --reporter junit | tee result.xml
      - store_artifacts:
          path: result.xml
      - store_test_results:
          path: result.xml

workflows:
  version: 2
  build-and-test:
    jobs:
      - build-and-test
